### ISSUE TITLE
Add checkbox event

### ISSUE THREAD

**Issue by TeaRX27** [TeaRX27/UE_CES#3]
Set all checkbox checked property to true

Checked checkbox - has candidate, enable textbox, vice versa

**Comment by maze-ro1** [comment]
waiting for approval to implement on every tab checkbox.//refer to central tab for checkbox.

button unchecks if another party is checked for the same position.
a notice (label) will appear when selecting a candidate. pre-texts can be modified easily.
created an array for votes. // arrayVote (int department, int position, int party)

department: 0- central, 1- cas, 2-cba, 3-ceng, 4-cfad
position: 0-pres, 1-vp, 2-sec, 3-treas, 4-audit, 5- pro, 6-bus mngr, 7-1, 8-2, 9-3, 10-4, 11-5
party: 0-tinig, 1-tugon
